# -*- coding: utf-8 -*-
"""task-8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tMPL39pkfWEBPk5LTe-DZTaRiQ8f92G7
"""

from pyspark.sql import SparkSession

spark = SparkSession.builder.getOrCreate()

df = spark.read.format('csv')\
.option('header', 'true') \
    .load('/content/sample_data/dataset.csv')

df.show()